config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :postulation
  devise_for :users

  root 'pages#index'
  get 'pages/index'
  get 'pages/empleos'
  get 'pages/vista_empleos'
  get 'pages/list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :postulations
  has_many :users, through: :postulations

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])
    @postulation = Postulation.find_or_create_by(job: @job, user: current_user )
    if @postulation.check == true
    @postulation.update(job: @job, user: current_user, check: false )
    else
    @postulation.update(job: @job, user: current_user, check: true )
    end
    if @job.save
      redirect_to postulation_index_path, notice: 'Tarea ingresada'
    else
      redirect_to jobs_path, alert: 'Tarea no ingresada'
    end
  end


  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :schedule, :tag, :rent )
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
  <%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

    <ul>
      <% job.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field form-group">
    <%= form.label 'Título' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label 'Descripción' %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label 'Horario (inicio y termino)' %>
    <%= form.text_field :schedule, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label 'Sueldo' %>
    <%= form.number_field :rent, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
  <% end %>

app/views/jobs/edit.html.erb
<div class="container">
  <h1>Editar postulación</h1>

  <%= render 'form', job: @job %>

  <%= link_to 'Show', @job %> |
  <%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Listado de empleos</h1>
  <% @jobs.each do |job| %>
  <div class="card">
    <div class="card-body">
      <h1><%= job.title %></h1>
      <h3><%= job.schedule %></h3>
      <p><%= job.description %></p>
      <%= link_to 'Ver postulantes', "#{pages_list_path}?id=#{job.id}", class: 'btn btn-info' %>
      <%= link_to 'Editar', edit_job_path(job), class: 'btn btn-success' %>
      <%= link_to 'Eliminar', job, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
  <% end %>

  <br>

  <%= link_to 'Registrar nuevo empleo', new_job_path %>
</div>

app/views/jobs/new.html.erb
<div class="container">
  <h1>Publicar empleo</h1>

  <%= render 'form', job: @job %>

  <%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @job.schedule %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @job.tag %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @job.rent %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>