config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :postulation
  devise_for :users

  root 'pages#index'
  get 'pages/index'
  get 'pages/empleos'
  get 'pages/vista_empleos'
  get 'pages/list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/empleos.html.erb
<div id="empleos" class="container">
      <% @jobs.each do |job| %>
      <div class="card">
        <div class="card-body">
          <h1><%= job.title %></h1>
          <% if Postulation.find_by(user_id: current_user.id , job_id: job.id, check: true) != nil %>
          <div class="proc">EN PROCESO DE POSTULACIÓN</div>
          <% end %>
          <h3><%= job.schedule %></h3>
          <p><%= job.description %></p>
          <a class="btn btn-primary"
          href="<%= pages_vista_empleos_path+'?id='+job.id.to_s %>">
          Revisar empleo
        </a>
        </div>
      </div>
      <% end %>
</div>

app/views/pages/index.html.erb
<!-- Header -->
<header class="masthead">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center">
      <h1 class="mx-auto my-0 text-uppercase">Senior Jobs</h1>
      <h2 class="text-white-50 mx-auto mt-2 mb-5">
        La mejor bolsa de empleo en Chile para la tercera edad.
      </h2>
      <%= link_to 'Iniciar sesión', new_user_session_path, class: 'btn btn-primary js-scroll-trigger' %>
    </div>
  </div>
</header>

app/views/pages/list.html.erb
<div id="list" class="container">
  <h1>Listado de postulantes</h1>
  <h2><%= Job.find(@job_id).title %></h2>
  <% @postulados.each do |postulation| %>
  <% user = User.find(postulation.user_id) %>
  <div class="card">
    <div class="card-body">
      <h1><%= user.name %></h1>
      <h3>RUT: <%= user.rut %></h3>
      <h3>Email: <%= user.email %></h3>
      <h3>Número de teléfono: <%= user.cellphone %></h3>
    </div>
  </div>
  <% end %>
  <%= link_to 'Volver', jobs_path %>
</div>

app/views/pages/vista_empleos.html.erb
<div id="vista_empleos" class="container">
  <h1><%= @job.title %></h1>
  <h3>Horario: <%= @job.schedule %></h3>
  <h3>Sueldo: $<%= number_with_delimiter @job.rent %></h3>
  <p><%= @job.description %></p>
  <form class="" action="index.html" method="post">
    <% if Postulation.find_by(user_id: current_user.id , job_id: @job.id, check: true) != nil %>
    <%= link_to "Dejar postulación", @job , class: 'btn btn-danger' %>
    <% else %>
    <%= link_to "Postular", @job , class: 'btn btn-primary' %>
    <% end %>
  </form>
</div>