config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :postulation
  devise_for :users

  root 'pages#index'
  get 'pages/index'
  get 'pages/empleos'
  get 'pages/vista_empleos'
  get 'pages/list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="bg-black small text-center text-white-50">
  <div class="container">
    Copyright &copy; SeniorJobs 2018
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
  <div class="container">
    <%= link_to 'SeniorJobs', root_path, class: 'navbar-brand js-scroll-trigger' %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menú
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <% if empleador? %>
          <!-- Insertar lo que ve el empleador -->
          <li class="nav-item">
            <%= link_to 'Ver listado de empleos', jobs_path, class: 'nav-link js-scroll-trigger' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Crear empleo', new_job_path, class: 'nav-link js-scroll-trigger' %>
          </li>
          <%else%>

          <!-- Insertar lo que ve el abuelo -->
          <li class="nav-item">
            <%= link_to 'Ver empleos', pages_empleos_path, class: 'nav-link js-scroll-trigger' %>
          </li>
          <%end%>

          <!-- Insertar lo que ven los 2 -->
          <li class="nav-item">
            <%= link_to 'Cerrar sesión', destroy_user_session_path, method: 'delete', class: 'nav-link js-scroll-trigger' %>
          </li>

        <% else %>
          <!-- No lgueado -->
        <li class="nav-item">
          <%= link_to 'Iniciar sesión', new_user_session_path, class: 'nav-link js-scroll-trigger' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link js-scroll-trigger' %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seniorjobs</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="page-top">
    <!-- Navigation -->
    <%= render 'layouts/navbar' %>
    <!-- Body -->
    <%= yield %>
    <!-- Footer -->
    <%= render 'layouts/footer' %>
  </body>
</html>